### ISSUE TITLE
Relation types according to RFC 5988

### ISSUE THREAD

**Issue by honzajavorek** [smizell/restfuljson#21]
If I understand it correctly, the prefix part of `prefix_url` or `prefixUrl` could play role of the relation type name, although the spec doesn't mention the [RFC5988](https://tools.ietf.org/html/rfc5988) anywhere. However, the RFC poses some restrictions on the relation type names:

```
relation-type  = reg-rel-type | ext-rel-type
reg-rel-type   = LOALPHA *( LOALPHA | DIGIT | "." | "-" )
ext-rel-type   = URI
```

This means the prefix can be only lowercase and contain only dots or dashes. Following strings are not valid: `createTask`, `create_task`

I'm not sure myself what's the point of this issue. Probably that this might limit the applications when implementing the RESTful JSON according to RFCs? Or maybe RESTful JSON intentionally doesn't link to the RFC so the application creators are not limited by the relation type name grammar?

**Comment by honzajavorek** [comment]
Also, there are standardized relation types such as `prev-archive`, which would need to be somehow ported to RESTful JSON, as they're neither `prevArchive` nor `prev_archive`.

**Comment by smizell** [comment]
This will depend on your implementation. The expectation is that you're using plain JSON and documenting the semantics around the properties somewhere else. This means that you should document the property that you're using, and defining how it relates to any outside type. 

> When you see the `nextUrl` property, it uses the registered `next` link relation type.

Something like that.

RESTful JSON (for most cases) is a shift in thinking from other hypermedia-based formats. Others are general-purpose formats that rely on link relations and media types, whereas RESTful JSON is more of a way to just add some links to your existing JSON.

**Comment by smizell** [comment]
This is also why we do not say we support all of the registered link relation types (minus `profile`). It's up to the user to define this semantic mapping.

**Comment by honzajavorek** [comment]
Okay, I think I understand now. So basically, if you want to use relation type names you can

- keep your link names simple and lowercase, in which case you can map them to relation type names implicitly (probably obvious to the documentation reader)
- use whatever you want, but then you should document the mapping (e.g. saying `prev_archive_url` translates to `prev-archive` relation type name)

Thanks!

**Comment by honzajavorek** [comment]
Well,

> Explicit is better than implicit.
> -- [PEP0020](https://www.python.org/dev/peps/pep-0020/)

...you should probably never rely on implicit mapping and just always document it explicitly 😏

**Comment by smizell** [comment]
This is correct. You don't _have_ to use registered relation types, but if you do, you need to map to them explicitly. If you want, you can make up your own types and map them to your JSON. Related, your relation types should not be constrained by JSON naming schemas in my opinion. Define your application semantics and then map those semantics to representation formats like JSON or whatever.

But most people aren't coming to RESTful JSON to use relation types. They're just adding in some links and documenting it. Not much more.
